---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/d3/d3po-working.html
    type: html
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/3/articles/3904/master/folder/figures/d3"
    url: "/users/3/articles/3904/master/file/figures/d3/d3po-working.html"
